#!/bin/bash
# Script written by W. Al Maawali  
# (c) 2016 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:
a=$(sudo dmidecode -s system-uuid);
b=$(sudo dmidecode -s system-serial-number);
c=$(sudo dmidecode |grep -w ID:|head -n1);
m=$a.$b.$c;
e=$(md5sum <<<$m);
IP_ADDR=$(sudo curl -s -m 30 "https://www.digi77.com/software/vpn/ipcheck.php?ko_hwid=$e")	
echo $IP_ADDR;
sudo echo $IP_ADDR > /home/kodachi/.kbase/.eeds-ipinfo;
SERVICE='tor-service';
if !(ps ax | grep -v grep | grep $SERVICE > /dev/null)
then		
	echo "Tor is not running";
else
TIP_ADDR=$(sudo curl --proxy socks5h://localhost:9050 -s -m 30 "https://www.digi77.com/software/kodachi/ipcheck.php?ko_hwid=$e")
	echo $TIP_ADDR;
	sudo echo $TIP_ADDR > /home/kodachi/.kbase/.eeds-tipinfo;
fi
echo "Done..";
#exit;



