#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2019 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

cd $(dirname $0) 
source Globalconfig;



notify-send -i $notifyIcon "Firewall disabled all traffic will be allowed";
sudo ufw --force reset;
sudo rm -f /etc/ufw/before.rules.*
sudo rm -f /etc/ufw/before6.rules.*
sudo rm -f /etc/ufw/after.rules.*
sudo rm -f /etc/ufw/after6.rules.*
sudo rm -f /etc/ufw/user.rules.*
sudo rm -f /etc/ufw/user6.rules.*
yes|sudo ufw reset;
sudo ufw disable;

#ip tables cleaner
# clean torify system
comment="kodachi_torify_system";
sudo iptables -t nat -S | grep "${comment}" | cut -d " " -f 2- | xargs -rL1 iptables -t nat -D
sudo iptables -S | grep "${comment}" | cut -d " " -f 2- | xargs -rL1 iptables -D

# Clean Tor dns
comment="kodachi_tor_dns";
sudo iptables -t nat -S | grep "${comment}" | cut -d " " -f 2- | xargs -rL1 iptables -t nat -D


exit 1;



