#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2018 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

cd $(dirname $0) 
source Globalconfig;



notify-send -i $notifyIcon "Firewall disabled all traffic will be allowed";
sudo ufw --force reset;
sudo rm -f /etc/ufw/before.rules.*
sudo rm -f /etc/ufw/before6.rules.*
sudo rm -f /etc/ufw/after.rules.*
sudo rm -f /etc/ufw/after6.rules.*
sudo rm -f /etc/ufw/user.rules.*
sudo rm -f /etc/ufw/user6.rules.*
yes|sudo ufw reset;
sudo ufw disable;

exit 1;



