#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2019 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

cd $(dirname $0) 
source Globalconfig;

 
sudo sed -i "/$LOGED_USER/d" /usr/share/lightdm/lightdm.conf.d/60-xubuntu.conf
sudo gpasswd -d $LOGED_USER nopasswdlogin;
notify-send -i $notifyIcon "You will be asked for user name and password at login"; 

exit 1;




