#!/bin/bash
# Script written by Warith Al Maawali
# (c) 2018 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

cd $(dirname $0) 
source Globalconfig;


sudo ufw --force reset;
sudo ufw default deny incoming;
sudo ufw default deny outgoing;
sudo ufw enable;
notify-send -i $notifyIcon "All Internet traffic is blocked now";
exit 1;
