#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2019 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:


cd $(dirname $0) 
source Globalconfig;


if [ ! -d $Mykodachi_path/tmp ]; then
	mkdir $Mykodachi_path/tmp;
	chown $LOGED_USER.$LOGED_USER $Mykodachi_path/tmp;
fi;

#NEW_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
NEW_UUID="mpWSUbCNvn8UjXumBnwZ5bRWDUAF0zDx@";
me=$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")

lockdir="$Mykodachi_path/tmp/$NEW_UUID$me";
mkdir $lockdir || {
    echo "lock directory exists. exiting"
    exit 1
}
# take pains to remove lock directory when script terminates
trap "rmdir $lockdir" EXIT INT KILL TERM

# rest of script here




# Get logged in user name
LOGED_USER=$(who | awk '{ print $1 }') 

# check if user has logged in
if [[ $LOGED_USER = *kodachi* ]]; then

 sleep 2;
 #notify-send -i $notifyIcon "Information display will start in few seconds";
 echo "Information display will start in few seconds";
 
 while true; do
	showConky=$(cat $Mykodachi_path/showconky);
	if [[ "$showConky" == *Yes* ]]
	then 
		if [[ $LOGED_USER = $EXEC_USER ]]; then
			SERVICE='conkyrc0';
			if !(ps ax | grep -v grep | grep $SERVICE > /dev/null)
			then		
				
				SERVICE='cairo-dock';
				if (ps ax | grep -v grep | grep $SERVICE > /dev/null)
				then
					#sleep 1;
					sudo killall conky;
					sleep 5;
					# use for cron for now killall is enopugh
					#export pid=`ps aux | grep conkyrc7 | awk 'NR==1{print $2}' | cut -d' ' -f1`;kill -9 $pid;
					sleep 1;
					conky -d -c "$Mykodachi_path/.conkyrc0";	
					sleep 1
					conky -d -c "$Mykodachi_path/.conkyrc1";	
					sleep 1
					conky -d -c "$Mykodachi_path/.conkyrc3";	
					sleep 1
					conky -d -c "$Mykodachi_path/.conkyrc2";	
					#sleep 1
					#conky -d -c "$Mykodachi_path/.conkyrc4";	
					# Fix Networkapplet showing twice
					pkill nm-applet && nm-applet & > /dev/null 	
				fi
			fi
		fi
	fi
	sleep 1;
	 
 done
	 
fi








 


 






