#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2019 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

cd $(dirname $0) 
source Globalconfig;

if(sudo systemctl unmask cups) 
then
	sudo systemctl start cups;
	sudo systemctl enable cups;
	notify-send -i $notifyIcon "Printer cups service enabled";
fi

exit 1;






 






