#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2019 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:


cd $(dirname $0) 
source Globalconfig;
  
for intf in /sys/class/net/*; do
	sudo ifconfig `basename $intf` down
	notify-send -i $notifyIcon "Taking $intf down";
done

sudo service tor stop;
sudo service openvpn stop; 
sudo killall tor;
sudo killall openvpn;
sudo service network-manager stop;
notify-send -i $notifyIcon "All network devices have been disabled";
exit 1;






 






