#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2019 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

#CS
#Find mount labels
#findmnt -lo source,target,fstype,label,options,used

cd $(dirname $0) 
source Globalconfig;

while true
do
	userInput=0;
	clear;
	echo "Please choose how would you like $OS_name to retrieve the ip addresses:";
	echo "";
	print_good "1) Decentralized get them from random public websites (recommended)";
	print_good "2) Centralized get them only from digi77.com ($OS_name website)";
	print_good "3) Exit";
	echo "";
	echo "Type the number of your selection";
	read n
	case $n in
		1) userInput=1;;
		2) userInput=2;;
		3) userInput=3;;
		*) print_error "sorry wrong value";sleep 1;;
	esac


	if [[ $userInput = "3" ]]
	then
		print_good "bye";
		echo "";
		exit 1;
	fi


	if [[ $userInput = "2" ]]
	then
		print_good "Running domain testeting script please wait for it to finish";
		echo "";
		#bash $Mykodachi_path/ipcheck -a digi77 
		the_d_value=$(cat $Mykodachi_path/ipretrievetype.txt);
		#while $the_d_value != 1 
		while [[ $the_d_value -eq 0 ]]; do
	        
			url2="https://www.digi77.com/software/vpn/ipcheckplain.php";
			echo "1" > $Mykodachi_path/ipretrievetype.txt
			echo $url2 > $Mykodachi_path/workingdomain.txt;		
			echo "Digi77" > $Mykodachi_path/iptypeletter;
			echo $url2 > $Mykodachi_path/workingdomain.txt;	
			sleep 5; 
			the_d_value=$(cat $Mykodachi_path/ipretrievetype.txt);
		done
		print_good "digi77.com site will be used as a domain";
		#notify-send -i $notifyIcon "Centralized selected digi77.com will be used as a domain for ip address retrievals";
		echo "";
		read -n 1 -s -r -p "${reset}Press any key to continue.....";
	fi


	if [[ $userInput = "1" ]]
	then
		print_good "Running domain testeting script please wait for it to finish";
		echo "";
		bash $Mykodachi_path/ipcheck -a other 
		print_good "Other sites will be used as a domain";
		#notify-send -i $notifyIcon "Decentralized selected other sites will be used as a domain for ip address retrievals";
		echo "";
		read -n 1 -s -r -p "${reset}Press any key to continue.....";
	fi


done;
