#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2019 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:


cd $(dirname $0) 
source Globalconfig;
   
for intf in /sys/class/net/*; do
	sudo ifconfig `basename $intf` up
	notify-send -i $notifyIcon "Bringing $intf up";
done
sudo service network-manager restart;
notify-send -i $notifyIcon "All network devices have been enabled";
exit 1;






 






