#!/bin/bash
# Script written by Warith Al Maawali
# (c) 2018 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here: 
cd $(dirname $0) 
source Globalconfig;




sudo swapoff -a;
sudo swapon -a;
#sudo sync; sudo echo 3 > /proc/sys/vm/drop_caches
#sudo sync && sudo bash -c 'echo 3 > /proc/sys/vm/drop_caches';
sudo sync && sudo echo 3 | sudo tee /proc/sys/vm/drop_caches;
sudo free -h
notify-send -i $notifyIcon "Ram-cache and the swap got cleared";
exit 1;
