#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2018 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

# Do not change the following settings at all or Kodachi will break for sure! Unless you know what you are doing!
 
Kodachi_version=5.7;
LOGED_USER=$(who | awk '{ print $1 }'|head -1);
EXEC_USER=${SUDO_USER:-$USER};
Myhome_path="/home/$LOGED_USER";
Mykodachi_path="/home/$LOGED_USER/.kbase"; 
Mykodachi_tmp_path="/home/$LOGED_USER/.kbase/tmp"; 
Mykodachi_dns_path="/home/$LOGED_USER/.kbase/dns";  
VPN_configs_path="/home/$LOGED_USER/Own_VPN_Config";
Kodachi_web_dir="https://digi77.com/software/kodachi";
VPN_gate_ovpn_dir="/home/$LOGED_USER/Own_VPN_Config/vpngateovpnfiles";
VPN_nord_ovpn_dir="/home/$LOGED_USER/Own_VPN_Config/vpnnordovpnfiles";
VPN_kern_ovpn_dir="/home/$LOGED_USER/Own_VPN_Config/vpnkernovpnfiles";
VPN_hideme_ovpn_dir="/home/$LOGED_USER/Own_VPN_Config/vpnhidemeovpnfiles";
VPN_proton_ovpn_dir="/home/$LOGED_USER/Own_VPN_Config/vpnprotonovpnfiles";
notifyIcon="$Mykodachi_path/icons/icons8-shield-48.png";

red=`tput setaf 1`
yellow=`tput setaf 3`
blue=`tput setaf 4`;
green=`tput setaf 2`;
cayn=`tput setaf 6`;
white=`tput setaf 7`;
reset=`tput sgr0`


lsb_D=$(lsb_release -s -d)
xP=$(id -u $LOGED_USER)
if [[ $xP == *990* ]] 
then
	if [[ $lsb_D != *Kodachi* ]]
	then
		sudo sed -i "s/^DISTRIB_DESCRIPTION=.*$/DISTRIB_DESCRIPTION=\"Kodachi\"/" /etc/lsb-release;
	fi
fi 

OS_name=$(lsb_release -s -d);



 
