#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2018 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

cd $(dirname $0) 
source Globalconfig;






netIP='google.com'; 
ping -c1 -W 2 "$netIP" &> /dev/null
if [ $? -eq 0 ]; 
then

	torifySystem=$(cat $Mykodachi_path/torifysystemstatus);
	if [[ "$torifySystem" == *No* ]]
	then

		echo "Race will start now fasten your seat belts ☺";
		notify-send -i $notifyIcon "HideMeVPN speed test will start now";
		rm -f $Mykodachi_tmp_path/hidemevppingtest.txt
		rm -f $Mykodachi_tmp_path/hidemevppingtest.txt.2
		rm -f $VPN_configs_path/speedtests/hideme_speed_test_results.txt
		
		if [ ! -d $VPN_configs_path/speedtests ]; then
			mkdir $VPN_configs_path/speedtests;
			chown $LOGED_USER.$LOGED_USER $VPN_configs_path/speedtests;
		fi;
		
		
		

		i=1;
		servercount=$(ls $VPN_hideme_ovpn_dir/*|wc -l)
		FILES=$VPN_hideme_ovpn_dir/*

		for f in $FILES
		do	     
				 
			theIP=$(cat $f|grep "^[^#;]"|grep 'remote '|awk  '{print $2}'); 
			avg=$(fping -B 1.0 -t 1000 -i 1 -r 0 -e -c 1 -q $theIP 2>&1 | awk -F'/' '{print $8}')
			f=$(echo $f| sed "s/.*\///"); 
			theCountry=$(geoiplookup $theIP|cut -d : -f 2|cut -d , -f 2|sed 's/^ *//;s/ *$//');
			echo "$f $theCountry $theIP=$avg" >> $Mykodachi_tmp_path/hidemevppingtest.txt

			# Calculate percentage of server testing process
			percentage=$((($i*100)/$servercount));
			echo -ne "${cayn}Testing $theIP server for latency using ping ($i \ $servercount) $percentage %  \033[0K\r${reset}"
			i=$((i+1))	
			
			done
				
			# Re-order and sort latency test results, save to new temp result file
			cat $Mykodachi_tmp_path/hidemevppingtest.txt | awk -F[=] '{ t=$1;$1=$2;$2=t;print; }' | sort -n > $Mykodachi_tmp_path/hidemevppingtest.txt.2;

		# Save all ping result file lines to final result file as long as they start with a ping value
		while read line; do
			firstcol=$(echo $line | awk '{print $1}')
			re='^[0-9]+([.][0-9]+)?$'

			if [[ $firstcol =~ $re ]] ; then
				echo $line >> $VPN_configs_path/speedtests/hideme_speed_test_results.txt;
			fi
		done < $Mykodachi_tmp_path/hidemevppingtest.txt.2	
		echo -e "\n";	  
		echo -e "\n${cayn}Top 10 HideMeVPN Servers by latency (ping)${reset}"
			echo "================================"
			cat $VPN_configs_path/speedtests/hideme_speed_test_results.txt | sort -n | head -10 
			the10=$(cat $VPN_configs_path/speedtests/hideme_speed_test_results.txt | sort -n | head -10 );	
		echo -e "\n";	     

		sudo chown $LOGED_USER.$LOGED_USER $Mykodachi_tmp_path/hidemevppingtest.txt.2;
		sudo chown $LOGED_USER.$LOGED_USER $Mykodachi_tmp_path/hidemevppingtest.txt;
		fastestserver=$(cat $VPN_configs_path/speedtests/hideme_speed_test_results.txt | head -1 | awk '{$1="";print}' | sed -e 's/^[[:space:]]*//')
		echo -e "${cayn}Fastest HideMeVPN server: ${green}$fastestserver${reset}\n";
		echo -e "\n";	
		echo "HideMeVPN speed test results saved in:"
		echo $VPN_configs_path/speedtests/hideme_speed_test_results.txt; 
		echo -e "\n";	
		echo "To use any of the above profiles change the variables in:"
		echo $VPN_configs_path/hidemevpnsetup; 
		chown $LOGED_USER.$LOGED_USER $VPN_configs_path/speedtests/hideme_speed_test_results.txt ;
		notify-send -t 30000 -i $notifyIcon "Fastest HideMeVPN server: 
$fastestserver

Top 10 HideMeVPN Servers by latency (ping):
$the10

HideMeVPN speed test results saved in:
$VPN_configs_path/speedtests/hideme_speed_test_results.txt

To use any of the above profiles change the variables in:
$VPN_configs_path/hidemevpnsetup";

	else
		notify-send -i $notifyIcon "Please disable Torified system first then run the script again!"
		echo "Please disable Torified system first then run the script again!"
	fi
	echo -e "\n\n";
else
	notify-send -i $notifyIcon "Please connect to Internet first!";
    exit 1;
fi
exit 1




