#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2019 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

cd $(dirname $0) 
source Globalconfig;




# Check status 
#sysctl -a|grep disable_ipv6

v1="net.ipv6.conf.all.disable_ipv6 = 1";
v2="net.ipv6.conf.default.disable_ipv6 = 1";
v3="net.ipv6.conf.lo.disable_ipv6 = 1";
v4="net.ipv6.conf.tun0.disable_ipv6 = 1";
sudo sed -i "/$v1/d" /etc/sysctl.conf
sudo sed -i "/$v2/d" /etc/sysctl.conf
sudo sed -i "/$v3/d" /etc/sysctl.conf
sudo sed -i "/$v4/d" /etc/sysctl.conf
echo -n "0" > /proc/sys/net/ipv6/conf/all/disable_ipv6;
sudo sysctl -p;
# Alternative way but I use both to be sure
sysctl -w net.ipv6.conf.all.disable_ipv6=0
sysctl -w net.ipv6.conf.default.disable_ipv6=0


notify-send -i $notifyIcon "IPv6 enabled"; 

exit 1







