#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2018 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:
cd $(dirname $0) 
source Globalconfig;




showtitle() {
clear
stdcol="\e[0m"
echo -e "\n${green} =============================="
echo " |    Important Notice        |"
echo -e " ==============================\n"

}

showtitle

echo -e "\n";
echo "${cayn}Installation is almost done ☺";
echo -e "\n";
bash $Mykodachi_path/beeper > /dev/null 2>&1;
#sleep 2;
echo "Be aware that everything you do will be saved permanently to the system! ";
sleep 4; 
echo -e "\n";
echo "${red}By doing so you also lost 10 scores from the security scoring scheme ☹"; 
sleep 4;
echo -e "\n";
echo "${cayn}Kodachi will shutdown in 30 seconds to finalize the installation"; 
sleep 4;
echo -e "\n";
echo "You can cancel the auto shutdown by closing this window to do it later manually but the sysetm will be slow!";
sleep 4;
echo -e "\n";
source $Mykodachi_path/progressbar 
progress_bar 30;
echo -e "\n";
echo "Shutting down the system....";
sleep 5;
shutdown -h now;
exit 1


