#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2019 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:


cd $(dirname $0) 
source Globalconfig;
x=$(find /sys/class/net ! -type d | xargs --max-args=1 realpath  | awk -F\/ '/pci/{print $NF}'|head -n1 | sed -e 's/\s.*$//');
xNet=$(ip route get 8.8.8.8 | sed -nr 's/.*dev ([^\ ]+).*/\1/p');
IP='google.com';



if [ ! -d $Mykodachi_path/tmp ]; then
	mkdir $Mykodachi_path/tmp;
	chown $LOGED_USER.$LOGED_USER $Mykodachi_path/tmp;
fi;

#NEW_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
NEW_UUID="Usilrx2HfsusaRFGqGnd0cTuZ0s1a87e@";
me=$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")

lockdir=$Mykodachi_path/tmp/$NEW_UUID$me
mkdir $lockdir || {
    echo "lock directory exists. exiting"
    exit 1
}
# take pains to remove lock directory when script terminates
trap "rmdir $lockdir" EXIT INT KILL TERM 

# rest of script here

 

# First boot message
#xP=$(id -u $LOGED_USER)
if [[ $xP == 1000 ]] 
then
	firstboot=$(cat $Mykodachi_path/firstboot);	 
	if [[ "$firstboot" == 1 ]]
	then
		sleep 30;
		echo "0" > $Mykodachi_path/firstboot;
		xfce4-terminal -e 'bash -c "sudo bash ~/.kbase/kodachifirstboot; bash"' -T "Completing Installation.." ;	
		sudo bash /home/$USER/.kbase/sshrkeys;	
		#exit 1; 
	fi
else
	sudo bash /home/$USER/.kbase/sshrkeys;
	sudo service unattended-upgrades stop;
	sleep 30;
	xfdesktop -A;

fi



# Start up check connection
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
	#notify-send -i $notifyIcon "Internet found no issues do nothing bye";
	echo "Net found exit";
	exit 1;
else
	#initilize the network
	echo "Dhclient the smart way";	
	for i in $( nmcli device status | awk '{print $1}' );
	do
		if [[ $i != "DEVICE" ]]
		then
			echo "Dhcp for:$i";
			sudo timeout 60 sudo dhclient $i;
		fi
	done

	echo "initilize the network done";
fi


# Fix audicity bug
sudo rm -f -r /var/tmp/audacity-kodachi/




sleep 600;
echo "Sleep of 600 over";


# If kodachi username has been changed warn the user
if [[ "$LOGED_USER" != *kodachi* ]]; then 
	notify-send -t 50000 -i $notifyIcon "Warning! $OS_name will not function properly!
You have changed the logged-in user name from kodachi to $LOGED_USER 
If you would like for $OS_name to function properly please login with the user name kodachi";	
	sleep 3;
filost

# Start up check connection
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  #notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  echo "Net found exit";
  exit 1;
else
	notify-send -t 20000 "No Internet found Kodachi needs Internet to work! 
so far I will try to fix it by few known methods 
each will have 30 seconds pause in between
to give you a chance to reconnect your wifi or ethernet";
	IP='digi77.com';
	echo "Switch domain from google to digi77.com";
	echo "Dhcclient the smart way";	
	for i in $( nmcli device status | awk '{print $1}' );
	do
		if [[ $i != "DEVICE" ]]
		then
			echo "Dhcp for:$i";
			sudo timeout 60 sudo dhclient $i;

		fi
	done
fi
sleep 2

# Method 0
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	#Manual boring way :p
	echo "Will dhclient the boring way";
	if !(sudo timeout 60 sudo dhclient $xNet)
	then
		if !(sudo timeout 60 sudo dhclient $x)
		then
			if !(sudo timeout 60 sudo dhclient wlp2s0)
			then
				if !(sudo timeout 60 sudo dhclient wlp3s0)
				then
					if !(sudo timeout 60 sudo dhclient wlx18a6f71995d8)
					then
						if(sudo timeout 60 sudo dhclient eth0)
						then
							sudo timeout 60 sudo dhclient wlan0;
						fi
					fi
				fi
			fi	
		fi
	fi
fi

sleep 30;

# Method 1
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	SERVICE='openvpn';
    if (ps ax | grep -v grep | grep $SERVICE > /dev/null)
    then
		notify-send -i $notifyIcon "No Internet found trying method 1:  shutdown vpn then
Restart Network-Manger";
		sudo killall -SIGINT openvpn;
		sudo service network-manager restart;	
		IP='google.com';	
		echo "Switch domain from digi77.com to google";
	fi
fi
sleep 5


# Method 1b
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 1B:  Clear firewalls";
	sudo bash $Mykodachi_path/allowalltraffic;		
	IP='digi77.com';	
fi
sleep 5





# Method 2 
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 2: ifconfig down and up for: $x and $xNet" ;
	sudo ifconfig $x down;
	sudo ifconfig $x up;
	sudo ifconfig $xNet down;
	sudo ifconfig $xNet up;
	IP='digi77.com';
	echo "Switch domain from google to digi77.com";	
fi
#sleep 3


# Method 3 
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 3: dhclient $x and $xNet" ;
	sudo timeout 60 sudo dhclient $x;
	sudo timeout 60 sudo dhclient $xNet;	
	IP='google.com';	
	echo "Switch domain from digi77.com to google";
fi
#sleep 3




# Method 4
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 4: ifconfig down and up for $x $xNet eth0 and wlan0"
	# Try to get interface again
	x=$(find /sys/class/net ! -type d | xargs --max-args=1 realpath  | awk -F\/ '/pci/{print $NF}'|head -n1 | sed -e 's/\s.*$//')
	sudo ifconfig eth0 down;
	sudo ifconfig wlan0 down;
	sudo ifconfig $x down;
	sudo ifconfig $xNet down;
	sudo ifconfig wlp3s0 down;
	sudo ifconfig wlp2s0 down;
	sudo ifconfig wlx18a6f71995d8 down;
	sudo ifconfig eth0 up;
	sudo ifconfig wlan0 up;
	sudo ifconfig $x up;
	sudo ifconfig $xNet up;
	sudo ifconfig wlp3s0 up;
	sudo ifconfig wlp2s0 up;
	sudo ifconfig wlx18a6f71995d8 up;
	IP='digi77.com';
	echo "Switch domain from google to digi77.com";	
	
fi
#sleep 3



# Method 5 
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 5: dhclient wlan0"
	sudo timeout 60 sudo dhclient wlan0;	
	IP='google.com';	
	echo "Switch domain from digi77.com to google";
fi
#sleep 3



# Method 6
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 6: dhclient eth0;"
	sudo timeout 60 sudo dhclient eth0;	
	IP='digi77.com';
	echo "Switch domain from google to digi77.com";	
fi



# Method 7
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 7: dhclient $x and $xNet";
	sudo timeout 60 sudo dhclient $x;
	sudo timeout 60 sudo dhclient $xNet;	
	IP='google.com';	
	echo "Switch to ip 1.1.1.1";
fi



# Method 8
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 8: wlp3s0"
	sudo timeout 60 sudo dhclient wlp3s0;	
	IP='google.com';	
	echo "Switch to ip 1.1.1.1";
fi

# Method 9
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 9: wlp2s0"
	sudo timeout 60 sudo dhclient wlp2s0;	
	IP='google.com';	
	echo "Switch to ip 1.1.1.1";
fi

# Method 10
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 10: wlx18a6f71995d8"
	sudo timeout 60 sudo dhclient wlx18a6f71995d8;	
	IP='google.com';	
	echo "Switch to ip 1.1.1.1";
fi



 


# Advice 
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
	notify-send -t 20000 "Internet found no issues do nothing bye";
	exit 1;
else
	notify-send -t 20000 "Failed to fix your Internet run the following command on terminal: 
sudo service network-manager restart;"
fi


exit 1;
