#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2018 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

cd $(dirname $0) 
source Globalconfig;



#Set time  sync and exit
sudo screenfetch -D gnu;
echo "Will sync time shortly";
sleep 5;
sudo service ntp stop;
sudo service ntp start;
sudo ntpq -p;
echo $(date);
sleep 5;
exit 1;
