#!/bin/bash
# Script written by Warith Al Maawali
# (c) 2018 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

cd $(dirname $0) 
source Globalconfig;
hV="";


if [ ! -d $Mykodachi_path/tmp ]; then
	mkdir $Mykodachi_path/tmp;
	chown $LOGED_USER.$LOGED_USER $Mykodachi_path/tmp;
fi;

#NEW_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
NEW_UUID="PpL5r6oKECy38aprdOaoxpgSzR4QWEMa@";
me=$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")

lockdir=$Mykodachi_path/tmp/$NEW_UUID$me
mkdir $lockdir || {
    echo "lock directory exists. exiting"
    exit 1
}
# take pains to remove lock directory when script terminates
trap "rmdir $lockdir" EXIT INT KILL TERM

function setTheconky()
{
	    notify-send -i $notifyIcon "Screen fonts will be adjusted shortly if you don't like the size
You can always change it from the Panic room then disable the auto font adjustment";
		sleep 30;				
		if [[ $hV -ge 1600 ]]
		then					
			#echo "7" > $Mykodachi_path/screenfontsize
			#bash $Mykodachi_path/decfont
			oldFontSize=$(cat $Mykodachi_path/screenfontsize);
			newFontSize=16;	
			rpl -i "size=$oldFontSize" "size=$newFontSize" $Mykodachi_path/.conkyrc*
			rpl -i "gap_x 220" "gap_x 330" $Mykodachi_path/.conkyrc2*
			rpl -i "gap_x 480" "gap_x 715" $Mykodachi_path/.conkyrc0*
			rpl -i "gap_x 480" "gap_x 715" $Mykodachi_path/.conkyrc1*
			echo $newFontSize > $Mykodachi_path/screenfontsize
			notify-send -i $notifyIcon "Font size changed from: $oldFontSize to: $newFontSize"; 
		else		
		if [[ $hV -gt 1300 ]]
		then					
			oldFontSize=$(cat $Mykodachi_path/screenfontsize);
			newFontSize=12;	
			rpl -i "size=$oldFontSize" "size=$newFontSize" $Mykodachi_path/.conkyrc*
			rpl -i "gap_x 330" "gap_x 220" $Mykodachi_path/.conkyrc2*
			rpl -i "gap_x 715" "gap_x 480" $Mykodachi_path/.conkyrc0*
			rpl -i "gap_x 715" "gap_x 480" $Mykodachi_path/.conkyrc1*
			echo $newFontSize > $Mykodachi_path/screenfontsize
			notify-send -i $notifyIcon "Font size changed from: $oldFontSize to: $newFontSize"; 
		else		
		if [[ $hV -gt 1000 ]]
		then
			oldFontSize=$(cat $Mykodachi_path/screenfontsize);
			newFontSize=10;	
			rpl -i "size=$oldFontSize" "size=$newFontSize" $Mykodachi_path/.conkyrc*
			rpl -i "gap_x 330" "gap_x 220" $Mykodachi_path/.conkyrc2*
			rpl -i "gap_x 715" "gap_x 480" $Mykodachi_path/.conkyrc0*
			rpl -i "gap_x 715" "gap_x 480" $Mykodachi_path/.conkyrc1*
			echo $newFontSize > $Mykodachi_path/screenfontsize
			notify-send -i $notifyIcon "Font size changed from: $oldFontSize to: $newFontSize"; 
		else	
		if [[ $hV -gt 800 ]]
		then					
			oldFontSize=$(cat $Mykodachi_path/screenfontsize);
			newFontSize=9;	
			rpl -i "size=$oldFontSize" "size=$newFontSize" $Mykodachi_path/.conkyrc*
			rpl -i "gap_x 330" "gap_x 220" $Mykodachi_path/.conkyrc2*
			rpl -i "gap_x 715" "gap_x 480" $Mykodachi_path/.conkyrc0*
			rpl -i "gap_x 715" "gap_x 480" $Mykodachi_path/.conkyrc1*
			echo $newFontSize > $Mykodachi_path/screenfontsize
			notify-send -i $notifyIcon "Font size changed from: $oldFontSize to: $newFontSize"; 
		else				
		if [[ $hV -gt 700 ]]
		then					
			oldFontSize=$(cat $Mykodachi_path/screenfontsize);
			newFontSize=8;	
			rpl -i "size=$oldFontSize" "size=$newFontSize" $Mykodachi_path/.conkyrc*
			rpl -i "gap_x 330" "gap_x 220" $Mykodachi_path/.conkyrc2*
			rpl -i "gap_x 715" "gap_x 480" $Mykodachi_path/.conkyrc0*
			rpl -i "gap_x 715" "gap_x 480" $Mykodachi_path/.conkyrc1*
			echo $newFontSize > $Mykodachi_path/screenfontsize
			notify-send -i $notifyIcon "Font size changed from: $oldFontSize to: $newFontSize"; 
		else
		if [[ $hV -lt 700 ]]
		then				
			oldFontSize=$(cat $Mykodachi_path/screenfontsize);
			newFontSize=6;	
			rpl -i "size=$oldFontSize" "size=$newFontSize" $Mykodachi_path/.conkyrc*
			rpl -i "gap_x 330" "gap_x 220" $Mykodachi_path/.conkyrc2*
			rpl -i "gap_x 715" "gap_x 480" $Mykodachi_path/.conkyrc0*
			rpl -i "gap_x 715" "gap_x 480" $Mykodachi_path/.conkyrc1*
			echo $newFontSize > $Mykodachi_path/screenfontsize
			notify-send -i $notifyIcon "Font size changed from: $oldFontSize to: $newFontSize"; 
		fi
		fi
		fi
		fi
		fi
		fi
	
} 

# check if user has logged in
if [[ $LOGED_USER = $EXEC_USER ]]; then
	function get_res {
		echo $(xrandr -q | awk -F'current' -F',' 'NR==1 {gsub("( |current)","");print $2}')
	}
	sleep 30;
	res1=$(get_res)
    hV=$(echo $res1|cut -d x -f 2)
    fontforce=$(cat $Mykodachi_path/forcefonts);
	if [[ "$fontforce" == *Yes* ]]
	then
		setTheconky;
	fi
	while true; do
		sleep 1
		res2=$(get_res)
		if [ "$res1" != "$res2" ]; then
			notify-send -i $notifyIcon "Screen resolution has been modified 
The display will restart now";
			sudo killall conky;	
			hV=$(echo $res2|cut -d x -f 2)
			echo $hV;
			fontforce=$(cat $Mykodachi_path/forcefonts);
			if [[ "$fontforce" == *Yes* ]]
			then
				
				setTheconky;				
			
			fi

		fi
		res1=$res2
	  
	  
			 
	done

fi

