#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2019 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:


cd $(dirname $0) 
source Globalconfig;

unset torifiedwason


torifySystem=$(cat $Mykodachi_path/torifysystemstatus);
if [[ "$torifySystem" == *Yes* ]]
then
	torifiedwason="Yes";
fi

echo "0" > /home/$LOGED_USER/.kbase/torenabled
echo "0" > /home/$LOGED_USER/.kbase/torenablednovpn
echo "No" >  $Mykodachi_path/torifysystemstatus

# clean torify system
comment="kodachi_torify_system";
sudo iptables -t nat -S | grep "${comment}" | cut -d " " -f 2- | xargs -rL1 iptables -t nat -D
sudo iptables -S | grep "${comment}" | cut -d " " -f 2- | xargs -rL1 iptables -D

# Clean Tor dns
comment="kodachi_tor_dns";
sudo iptables -t nat -S | grep "${comment}" | cut -d " " -f 2- | xargs -rL1 iptables -t nat -D


# Set DNS to Dnscrypt
cat $Mykodachi_path/dns/dns0 > $Mykodachi_path/dns/dns1;
sudo cat $Mykodachi_path/dns/dns0 > /etc/resolv.conf;
sudo service dnscrypt-proxy restart   
#sudo service dnscrypt-proxy start
echo "1" > $Mykodachi_path/dns/autodnscrypt;
sudo cat $Mykodachi_path/dns/dns0 > /etc/resolv.conf;
if [[ "$torifiedwason" == *Yes* ]]
then
	echo "-" > $Mykodachi_path/.eeds-ipinfo;
	echo "-" > $Mykodachi_path/.eeds-tipinfo;
	echo "1" > /home/$LOGED_USER/.kbase/actionpicker
fi

if systemctl is-active tor.service > /dev/null 2>&1;  
then
	sudo /etc/init.d/tor stop;	
fi
notify-send -i $notifyIcon "Tor client disabled"; 

