#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2019 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

cd $(dirname $0) 
source Globalconfig;


#xP=$(id -u $LOGED_USER);
if [[ $xP == 1000 ]]  
then

	reply=$1;

	
	if [[ "$reply" = *"on"* ]]
	then


		if (sudo swapon -a)
		then
			numberOfcSwaps=$(sudo swapon -s|grep -v Filename|wc -l);
			notify-send -i $notifyIcon "Swap memory enabled
Total swap files: $numberOfcSwaps";
			echo "1" > $Mykodachi_path/swapstatus;
			chown $LOGED_USER.$LOGED_USER $Mykodachi_path/swapstatus;
		else
			notify-send -i $notifyIcon "Swap memory enabling failed";
			exit 1;
		fi
	fi
	
		
		
	if [[ "$reply" = *"off"* ]]
	then

		if (sudo swapoff -a)
		then
			notify-send -i $notifyIcon "Swap memory disabled";
			echo "0" > $Mykodachi_path/swapstatus
			chown $LOGED_USER.$LOGED_USER $Mykodachi_path/swapstatus;
		else
			notify-send -i $notifyIcon "Swap memory disabling failed";
			exit 1;
		fi
	fi
	


else

	print_error "$OS_name swap is for installed system only";
	notify-send -i $notifyIcon "$OS_name swap is for installed system only";
	exit 1;
fi

exit 1;
