#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2018 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:
cd $(dirname $0) 
source Globalconfig;



notify-send -i $notifyIcon "Wiping memory then shutting down later";
sleep 2;
notify-send -i $notifyIcon "If you are on live system the OS will freez later on";
echo "Wiping your memory before shutdown....";
sleep 10;
sudo sdmem -v;
sleep 5;
sudo shutdown -h now;
exit 1;
