#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2022 Founder of Eagle Eye Digital Solutions
# Discord channel https://discord.gg/KEFErEx
# Twitter http://twitter.com/warith2020
# Linkedin http://www.linkedin.com/in/warith1977
# http://www.digi77.com
# http://www.om77.net
# Kodachi  OS/Software/Code are strictly protected by LICENSE terms at /home/kodachi/LICENSE
#
#
# script starts here:


cd $(dirname $0) 
source Globalconfig;
x=$(find /sys/class/net ! -type d | xargs --max-args=1 realpath  | awk -F\/ '/pci/{print $NF}'|head -n1 | sed -e 's/\s.*$//');
xNet=$(ip route get 8.8.8.8 | sed -nr 's/.*dev ([^\ ]+).*/\1/p');




IP=$(cat $Jason_web_file_name| jq -r '.ServerFeed6[].Netcheckdomain1'|xargs);
echo "interface used: $x" ;
echo "interface used for net: $xNet" ;

# Start up check connection
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -t 20000 "No Internet found Kodachi needs Internet to work! 
so far I will try to fix it by few known methods 
each will have 30 seconds pause in between
to give you a chance to reconnect your wifi or ethernet";

	IP=$(cat $Jason_web_file_name| jq -r '.ServerFeed6[].Netcheckdomain1'|xargs);
	# Validate jsons here			
	if [[ ! -n "$IP" ]]
	then
		netIP="mail.com";
		print_error "Failed to get json variable IP setting it to: $IP";
	fi	
	echo "Switching domain to $IP";
	echo "Dhcclient the smart way";	
	for i in $( nmcli device status | awk '{print $1}' );
	do
		if [[ $i != "DEVICE" ]]
		then
			echo "Dhcp for:$i";
			sudo timeout 60 sudo dhclient $i;

		fi
	done
fi
sleep 2;

# Method 0
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	#Manual boring way :p
	echo "Will dhclient the boring way";
	if !(sudo timeout 60 sudo dhclient $xNet)
	then
		if !(sudo timeout 60 sudo dhclient $x)
		then
			if !(sudo timeout 60 sudo dhclient wlp2s0)
			then
				if !(sudo timeout 60 sudo dhclient wlp3s0)
				then
					if !(sudo timeout 60 sudo dhclient wlx18a6f71995d8)
					then
						if(sudo timeout 60 sudo dhclient eth0)
						then
							sudo timeout 60 sudo dhclient wlan0;
						fi
					fi
				fi
			fi	
		fi
	fi
fi

 

sleep 30;
# Method 1
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	SERVICE='openvpn';
    if (ps ax | grep -v grep | grep $SERVICE > /dev/null)
    then
		notify-send -i $notifyIcon "No Internet found trying method 1:  shutdown vpn then
Restart Network-Manger";
		sudo killall -SIGINT openvpn;
		sudo service network-manager restart;	
		IP=$(cat $Jason_web_file_name| jq -r '.ServerFeed6[].Netcheckdomain2'|xargs);
		# Validate jsons here			
		if [[ ! -n "$IP" ]]
		then
			netIP="mail.com";
			print_error "Failed to get json variable IP setting it to: $IP";
		fi	
		echo "Switching domain to $IP";
	fi
fi
sleep 5


# Method 1b
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 1B:  Clear firewalls";
	sudo bash $Mykodachi_path/allowalltraffic;	
	IP=$(cat $Jason_web_file_name| jq -r '.ServerFeed6[].Netcheckdomain1'|xargs);
	# Validate jsons here			
	if [[ ! -n "$IP" ]]
	then
		netIP="mail.com";
		print_error "Failed to get json variable IP setting it to: $IP";
	fi	
	
fi
sleep 5


 



# Method 2 
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 2: ifconfig down and up for: $x and $xNet" ;
	sudo ifconfig $x down;
	sudo ifconfig $x up;
	sudo ifconfig $xNet down;
	sudo ifconfig $xNet up;
	IP=$(cat $Jason_web_file_name| jq -r '.ServerFeed6[].Netcheckdomain2'|xargs);
	# Validate jsons here			
	if [[ ! -n "$IP" ]]
	then
		netIP="mail.com";
		print_error "Failed to get json variable IP setting it to: $IP";
	fi	
	echo "Switching domain to $IP";
fi
#sleep 3


# Method 3 
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 3: dhclient $x and $xNet" ;
	sudo timeout 60 sudo dhclient $x;
	sudo timeout 60 sudo dhclient $xNet;	
	IP=$(cat $Jason_web_file_name| jq -r '.ServerFeed6[].Netcheckdomain3'|xargs);
	# Validate jsons here			
	if [[ ! -n "$IP" ]]
	then
		netIP="mail.com";
		print_error "Failed to get json variable IP setting it to: $IP";
	fi	
	echo "Switching domain to $IP";
fi
#sleep 3




# Method 4
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 4: ifconfig down and up for $x $xNet eth0 and wlan0"
	# Try to get interface again
	x=$(find /sys/class/net ! -type d | xargs --max-args=1 realpath  | awk -F\/ '/pci/{print $NF}'|head -n1 | sed -e 's/\s.*$//')
	sudo ifconfig eth0 down;
	sudo ifconfig wlan0 down;
	sudo ifconfig $x down;
	sudo ifconfig $xNet down;
	sudo ifconfig wlp3s0 down;
	sudo ifconfig wlp2s0 down;
	sudo ifconfig wlx18a6f71995d8 down;
	sudo ifconfig eth0 up;
	sudo ifconfig wlan0 up;
	sudo ifconfig $x up;
	sudo ifconfig $xNet up;
	sudo ifconfig wlp3s0 up;
	sudo ifconfig wlp2s0 up;
	sudo ifconfig wlx18a6f71995d8 up;
	IP=$(cat $Jason_web_file_name| jq -r '.ServerFeed6[].Netcheckdomain4'|xargs);
	# Validate jsons here			
	if [[ ! -n "$IP" ]]
	then
		netIP="mail.com";
		print_error "Failed to get json variable IP setting it to: $IP";
	fi	
	echo "Switching domain to $IP";
	
fi
#sleep 3



# Method 5 
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 5: dhclient wlan0"
	sudo timeout 60 sudo dhclient wlan0;	
	IP=$(cat $Jason_web_file_name| jq -r '.ServerFeed6[].Netcheckdomain1'|xargs);	
	# Validate jsons here			
	if [[ ! -n "$IP" ]]
	then
		netIP="mail.com";
		print_error "Failed to get json variable IP setting it to: $IP";
	fi	
	echo "Switching domain to $IP";
fi
#sleep 3



# Method 6
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 6: dhclient eth0;"
	sudo timeout 60 sudo dhclient eth0;	
	IP=$(cat $Jason_web_file_name| jq -r '.ServerFeed6[].Netcheckdomain2'|xargs);
	# Validate jsons here			
	if [[ ! -n "$IP" ]]
	then
		netIP="mail.com";
		print_error "Failed to get json variable IP setting it to: $IP";
	fi	
	echo "Switching domain to $IP";
fi



# Method 7
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 7: dhclient $x and $xNet";
	sudo timeout 60 sudo dhclient $x;
	sudo timeout 60 sudo dhclient $xNet;	
	IP=$(cat $Jason_web_file_name| jq -r '.ServerFeed6[].Netcheckdomain3'|xargs);
	# Validate jsons here			
	if [[ ! -n "$IP" ]]
	then
		netIP="mail.com";
		print_error "Failed to get json variable IP setting it to: $IP";
	fi	
	echo "Switch to ip 1.1.1.1";
fi

# Method 8
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 8: wlp3s0"
	sudo timeout 60 sudo dhclient wlp3s0;	
	IP=$(cat $Jason_web_file_name| jq -r '.ServerFeed6[].Netcheckdomain4'|xargs);
	# Validate jsons here			
	if [[ ! -n "$IP" ]]
	then
		netIP="mail.com";
		print_error "Failed to get json variable IP setting it to: $IP";
	fi	
	echo "Switch to ip 1.1.1.1";
fi

# Method 9
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 9: wlp2s0"
	sudo timeout 60 sudo dhclient wlp2s0;	
	IP=$(cat $Jason_web_file_name| jq -r '.ServerFeed6[].Netcheckdomain1'|xargs);
	# Validate jsons here			
	if [[ ! -n "$IP" ]]
	then
		netIP="mail.com";
		print_error "Failed to get json variable IP setting it to: $IP";
	fi	
	echo "Switch to ip 1.1.1.1";
fi

# Method 10
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
  notify-send -i $notifyIcon "Internet found no issues do nothing bye";
  exit 1;
else
	notify-send -i $notifyIcon "No Internet found trying method 10: wlx18a6f71995d8"
	sudo timeout 60 sudo dhclient wlx18a6f71995d8;	
	IP=$(cat $Jason_web_file_name| jq -r '.ServerFeed6[].Netcheckdomain2'|xargs);
	# Validate jsons here			
	if [[ ! -n "$IP" ]]
	then
		netIP="mail.com";
		print_error "Failed to get json variable IP setting it to: $IP";
	fi	
	echo "Switch to ip 1.1.1.1";
fi




# Advice 
wget --timeout=5 --waitretry=0 --tries=3 --retry-connrefused -q --spider "$IP" &> /dev/null
if [ $? -eq 0 ]; 
then
	notify-send -t 20000 "Internet found no issues do nothing bye";
	exit 1;
else
	notify-send -t 20000 "Failed to fix your Internet run the following command on terminal: 
sudo service network-manager restart;"
fi


exit 1;
