#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2022 Founder of Eagle Eye Digital Solutions
# Discord channel https://discord.gg/KEFErEx
# Twitter http://twitter.com/warith2020
# Linkedin http://www.linkedin.com/in/warith1977
# http://www.digi77.com
# http://www.om77.net
# Kodachi  OS/Software/Code are strictly protected by LICENSE terms at /home/kodachi/LICENSE
#
#
# script starts here:

cd $(dirname $0) 
source Globalconfig;




notify-send -i $notifyIcon "Downloading VPNGate servers" \ "This process will take time please wait";
#Clean up
rm -f -r $Mykodachi_tmp_path/vpngateconfigs;
rm -f $Mykodachi_tmp_path/vpngateconfigs.zip;

timeout 600 wget -O $Mykodachi_tmp_path/vpngateconfigs.zip "$Kodachi_web_dir/download.php?f=vpngateconfigs.zip" -q

unzip -o -P a30@06e61-79-34-88-A4-C3@ $Mykodachi_tmp_path/vpngateconfigs.zip -d $Mykodachi_tmp_path; 
chmod 755 $Mykodachi_tmp_path/vpngateconfigs -R;
mq=$(ls -1q $Mykodachi_tmp_path/vpngateconfigs/*.ovpn | wc -l);
sq="3";
echo $mq;
if [[ $mq -lt $sq ]] 
then
	notify-send -i $notifyIcon "Updating VPNGate servers: FAIL" \ "Please try again";
	rm -f $Mykodachi_tmp_path/vpngateconfigs.zip;
	exit 1
fi
rm -f -r $VPN_gate_ovpn_dir;
mv $Mykodachi_tmp_path/vpngateconfigs $VPN_gate_ovpn_dir
rm -f $Mykodachi_tmp_path/vpngateconfigs.zip
x=$(ls $VPN_gate_ovpn_dir|wc -l);
echo $x
notify-send -t 20000 -i $notifyIcon "Download complete now you can try to connect to VPNGate servers" "$(echo -e "VPNGate has $x ovpn files that were validated by $OS_name nodes\nVPNGate ovpn files location:\n$VPN_gate_ovpn_dir")";

exit 1


