#!/bin/bash
# Script written by Warith Al Maawali  s
# (c) 2022 Founder of Eagle Eye Digital Solutions
# Discord channel https://discord.gg/KEFErEx
# Twitter http://twitter.com/warith2020
# Linkedin http://www.linkedin.com/in/warith1977
# http://www.digi77.com
# http://www.om77.net
# Kodachi  OS/Software/Code are strictly protected by LICENSE terms at /home/kodachi/LICENSE
#
#
# script starts here:


cd $(dirname $0) 
source Globalconfig;


parm1=$1
	
oldFontSize=$(cat $Jason_file_name | jq -r .Screenfontsize);
if [[ "$oldFontSize" -lt 21 ]] && [[ "$oldFontSize" -gt 3 ]]
then
	if [[ ! -n $parm1 ]] 
	then
		newFontSize=$((oldFontSize-1));
	else
		newFontSize=$parm1
	fi
		
	echo $oldFontSize " - " $newFontSize;
	rpl -i "size=$oldFontSize" "size=$newFontSize" $Mykodachi_path/.conkyrc*
	if [[ $newFontSize -lt 13 ]]
	then	
		rpl -i "gap_x 350" "gap_x 220" $Mykodachi_path/.conkyrc2*;
		rpl -i "gap_x 780" "gap_x 500" $Mykodachi_path/.conkyrc0*;
		rpl -i "gap_x 725" "gap_x 480" $Mykodachi_path/.conkyrc1*;
		rpl -i "minimum_size 320 0" "minimum_size 220 0" $Mykodachi_path/.conkyrc1*;
	else
		rpl -i "gap_x 220" "gap_x 350" $Mykodachi_path/.conkyrc2*;
		rpl -i "gap_x 500" "gap_x 780" $Mykodachi_path/.conkyrc0*;
		rpl -i "gap_x 480" "gap_x 725" $Mykodachi_path/.conkyrc1*;
		rpl -i "minimum_size 220 0" "minimum_size 320 0" $Mykodachi_path/.conkyrc1*;
		
	fi
	notify-send -i $notifyIcon "Font size changed from: $oldFontSize to: $newFontSize"; 
	writeToJason "$newFontSize " "Screenfontsize"; 
else
	notify-send -i $notifyIcon "Font size $oldFontSize is minimum you can change to";

fi



exit 1;	
	
	
	
	
 






 






