#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2022 Founder of Eagle Eye Digital Solutions
# Discord channel https://discord.gg/KEFErEx
# Twitter http://twitter.com/warith2020
# Linkedin http://www.linkedin.com/in/warith1977
# http://www.digi77.com
# http://www.om77.net
# Kodachi  OS/Software/Code are strictly protected by LICENSE terms at /home/kodachi/LICENSE
#
#
# script starts here:

cd $(dirname $0) 
source Globalconfig;



#Set time  sync and exit
sudo screenfetch -D gnu;
print_good "Will sync time shortly";
sleep 5;
sudo service ntp stop;
sudo service ntp start;
sudo ntpq -p;
echo $(date);
sleep 5;
exit 1;
