#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2022 Founder of Eagle Eye Digital Solutions
# Discord channel https://discord.gg/KEFErEx
# Twitter http://twitter.com/warith2020
# Linkedin http://www.linkedin.com/in/warith1977
# http://www.digi77.com
# http://www.om77.net
# Kodachi  OS/Software/Code are strictly protected by LICENSE terms at /home/kodachi/LICENSE
#
#
# script starts here:

cd $(dirname $0) 
source Globalconfig;


showtitle() {
clear
stdcol="\e[0m"
echo -e "\n${green} =============================="
echo " |    $OS_name IP security Test   |"
echo -e " ==============================\n"

}

showtitle

	

#read -n 1 -s -r -p "${reset}Press any key to start.....";
#echo -e "\n"


print_good "Getting verifications domains";
arr=( $(cat $Jason_web_file_name | jq -r '.ServerFeed3.netStatusDomains[]') )
print_good "Done"
echo -e "\n";
sleep 1;

i=0 
while [ $i -lt ${#arr[@]} ] 
do   
    
    # Get domain only
	dO=$( echo ${arr[$i]} | sed -e 's|^[^/]*//||' -e 's|/.*$||');    
    print_good "Reporting your ip from $dO :";
    curl -s -m 30 ${arr[$i]}|xargs|tr -d " \t\n\r";
    echo -e "\n"
    i=`expr $i + 1` 
done
kodachiipcheck=$(cat $Jason_web_file_name | jq -r '.ServerFeed2[].kodachiipcheck'|xargs);
print_good "Reporting your ip digi77.com:";
TIP_ADDR=$(curl -s -m 30 $kodachiipcheck);
TIP_ADDR2=$(echo $TIP_ADDR|xargs|tr -d " \t\n\r");
echo $TIP_ADDR2;
echo -e "\n"
echo "----------------------------------------------------------------------";

# No Tor no torify use cloud flare safe list
toriffy_Status=$(cat $Jason_file_name | jq -r .Toriffystatus);
if [[ "$toriffy_Status" == *Yes* ]]
then	
	print_good "Getting verifications GeoIpdomains";
	arr2=( $(cat $Jason_web_file_name | jq -r '.ServerFeed4.iGgeoDomains[]') )
	echo -e "\n";
else
	print_good "Getting verifications GeoIpdomains";
	arr2=( $(cat $Jason_web_file_name | jq -r '.ServerFeed5.iGgeoDomainsCF[]') )
	echo -e "\n";

fi	
 
i=0 
while [ $i -lt ${#arr2[@]} ] 
do   

	template=$(echo ${arr2[$i]} | sed 's/###/'$TIP_ADDR2'/g');
	jqparm=$(echo $template|cut -d @ -f 2 );
	template=$(echo ${arr2[$i]} | sed 's/###/'$TIP_ADDR2'/g'|cut -d @ -f 1);
	
	# Get domain only
	dO=$( echo ${arr2[$i]} | sed -e 's|^[^/]*//||' -e 's|/.*$||');
   
	
    print_good "Reporting your Country from $dO :";
    curl -s -m 20 -X GET "$template" -H  "accept: application/json" | jq -r $jqparm
    echo -e "\n"
    i=`expr $i + 1` 
done

print_good "Reporting your Country from local geoip";
LgeoC=$(geoiplookup $TIP_ADDR2|cut -d : -f 2|cut -d , -f 2|sed 's/^ *//;s/ *$//'|tail -n 1);		
echo $LgeoC;
echo -e "\n";

if ! systemctl is-active tor.service > /dev/null 2>&1;  
then
	print_error "Tor is off skipping Tor ip check";
	echo "";
else
	read -n 1 -s -r -p "${reset}Press any key to start Tor ip check.....";
	echo -e "\n"

	echo "----------------------------------------------------------------------";
	i=0 
	while [ $i -lt ${#arr[@]} ] 
	do   
	
	    # Get domain only
		dO=$( echo ${arr[$i]} | sed -e 's|^[^/]*//||' -e 's|/.*$||');    
		print_good "Reporting your Tor ip from $dO :";
		torify curl -s -m 30 ${arr[$i]}|xargs|tr -d " \t\n\r";
		echo -e "\n"
		i=`expr $i + 1` 
	done
	
	print_good "Reporting your Tor ip digi77.com:";
	kodachiipcheck=$(cat $Jason_web_file_name | jq -r '.ServerFeed2[].kodachiipcheck'|xargs);
	TIP_ADDR=$(torify curl -s -m 30 $kodachiipcheck);
	TIP_ADDR2=$(echo $TIP_ADDR|xargs|tr -d " \t\n\r");
	echo $TIP_ADDR2;
	echo -e "\n";
	echo "----------------------------------------------------------------------";
	
	
	# No Tor no torify use cloud flare safe list
	toriffy_Status=$(cat $Jason_file_name | jq -r .Toriffystatus);
	if [[ "$toriffy_Status" == *Yes* ]]
	then
		print_good "Getting verifications GeoIpdomains";
		arr2=( $(cat $Jason_web_file_name | jq -r '.ServerFeed4.iGgeoDomains[]') )
		echo -e "\n";
	else
		print_good "Getting verifications GeoIpdomains";
		arr2=( $(cat $Jason_web_file_name | jq -r '.ServerFeed5.iGgeoDomainsCF[]') )
		echo -e "\n";

	fi	
	 
	i=0 
	while [ $i -lt ${#arr2[@]} ] 
	do   

		template=$(echo ${arr2[$i]} | sed 's/###/'$TIP_ADDR2'/g');
		jqparm=$(echo $template|cut -d @ -f 2 );
		template=$(echo ${arr2[$i]} | sed 's/###/'$TIP_ADDR2'/g'|cut -d @ -f 1);
		
		 # Get domain only
		dO=$( echo ${arr2[$i]} | sed -e 's|^[^/]*//||' -e 's|/.*$||');    
		print_good "Reporting your TOR Country from $dO :";
		curl -s -m 20 -X GET "$template" -H  "accept: application/json" | jq -r $jqparm
		echo -e "\n"
		i=`expr $i + 1` 
	done
	
print_good "Reporting your TOR Country from local geoip";
LgeoC=$(geoiplookup $TIP_ADDR2|cut -d : -f 2|cut -d , -f 2|sed 's/^ *//;s/ *$//'|tail -n 1);		
echo $LgeoC;	
echo -e "\n";			

fi 	
echo -e "\n";
print_good "Completed"
exit 1;
