#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2022 Founder of Eagle Eye Digital Solutions
# Discord channel https://discord.gg/KEFErEx
# Twitter http://twitter.com/warith2020
# Linkedin http://www.linkedin.com/in/warith1977
# http://www.digi77.com
# http://www.om77.net
# Kodachi  OS/Software/Code are strictly protected by LICENSE terms at /home/kodachi/LICENSE
#
#
# script starts here:

cd $(dirname $0) 
source Globalconfig;
hV="";


if [ ! -d $Mykodachi_path/tmp ]; then
	mkdir -p $Mykodachi_path/tmp;
	chown $LOGED_USER.$LOGED_USER $Mykodachi_path/tmp;
fi;

#NEW_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
NEW_UUID="PpL5r6oKECy38aprdOaoxpgSzR4QWEMa@";
me=$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")

lockdir=$Mykodachi_path/tmp/$NEW_UUID$me
mkdir $lockdir || {
    echo "lock directory exists. exiting"
    exit 1
}
# take pains to remove lock directory when script terminates
trap "rmdir $lockdir" EXIT INT KILL TERM

# rest of script here
sudo chown $LOGED_USER.$LOGED_USER $Mykodachi_path/tmp/$NEW_UUID$me;
	
# end script locker


function setTheconky()
{
	    notify-send -i $notifyIcon "Screen fonts will be adjusted shortly if you don't like the size
You can always change it from the Panic room then disable the auto font adjustment";
		sleep 30;				
		if [[ $hV -ge 1600 ]]
		then					
			
			oldFontSize=$(cat $Jason_file_name | jq -r .Screenfontsize);
			newFontSize=16;	
			rpl -i "size=$oldFontSize" "size=$newFontSize" $Mykodachi_path/.conkyrc*
			rpl -i "gap_x 220" "gap_x 350" $Mykodachi_path/.conkyrc2*
			rpl -i "gap_x 500" "gap_x 780" $Mykodachi_path/.conkyrc0*
			rpl -i "gap_x 480" "gap_x 725" $Mykodachi_path/.conkyrc1*
			rpl -i "minimum_size 220 0" "minimum_size 320 0" $Mykodachi_path/.conkyrc1*;
			writeToJason "$newFontSize " "Screenfontsize"; 
			notify-send -i $notifyIcon "screen font size changed from: $oldFontSize to: $newFontSize"; 
		else		
		if [[ $hV -gt 1300 ]]
		then					
			oldFontSize=$(cat $Jason_file_name | jq -r .Screenfontsize);
			newFontSize=12;	
			rpl -i "size=$oldFontSize" "size=$newFontSize" $Mykodachi_path/.conkyrc*
			rpl -i "gap_x 350" "gap_x 220" $Mykodachi_path/.conkyrc2*
			rpl -i "gap_x 780" "gap_x 500" $Mykodachi_path/.conkyrc0*
			rpl -i "gap_x 725" "gap_x 480" $Mykodachi_path/.conkyrc1*
			rpl -i "minimum_size 320 0" "minimum_size 220 0" $Mykodachi_path/.conkyrc1*;
			writeToJason "$newFontSize " "Screenfontsize"; 
			notify-send -i $notifyIcon "screen font size changed from: $oldFontSize to: $newFontSize"; 
		else		
		if [[ $hV -gt 1000 ]]
		then
			oldFontSize=$(cat $Jason_file_name | jq -r .Screenfontsize);
			newFontSize=10;	
			rpl -i "size=$oldFontSize" "size=$newFontSize" $Mykodachi_path/.conkyrc*
			rpl -i "gap_x 350" "gap_x 220" $Mykodachi_path/.conkyrc2*
			rpl -i "gap_x 780" "gap_x 500" $Mykodachi_path/.conkyrc0*
			rpl -i "gap_x 725" "gap_x 480" $Mykodachi_path/.conkyrc1*
			rpl -i "minimum_size 320 0" "minimum_size 220 0" $Mykodachi_path/.conkyrc1*;
			writeToJason "$newFontSize " "Screenfontsize"; 
			notify-send -i $notifyIcon "screen font size changed from: $oldFontSize to: $newFontSize"; 
		else	
		if [[ $hV -gt 800 ]]
		then					
			oldFontSize=$(cat $Jason_file_name | jq -r .Screenfontsize);
			newFontSize=9;	
			rpl -i "size=$oldFontSize" "size=$newFontSize" $Mykodachi_path/.conkyrc*
			rpl -i "gap_x 350" "gap_x 220" $Mykodachi_path/.conkyrc2*
			rpl -i "gap_x 780" "gap_x 500" $Mykodachi_path/.conkyrc0*
			rpl -i "gap_x 725" "gap_x 480" $Mykodachi_path/.conkyrc1*
			rpl -i "minimum_size 320 0" "minimum_size 220 0" $Mykodachi_path/.conkyrc1*;
			writeToJason "$newFontSize " "Screenfontsize"; 
			notify-send -i $notifyIcon "screen font size changed from: $oldFontSize to: $newFontSize"; 
		else				
		if [[ $hV -gt 700 ]]
		then					
			oldFontSize=$(cat $Jason_file_name | jq -r .Screenfontsize);
			newFontSize=8;	
			rpl -i "size=$oldFontSize" "size=$newFontSize" $Mykodachi_path/.conkyrc*
			rpl -i "gap_x 350" "gap_x 220" $Mykodachi_path/.conkyrc2*
			rpl -i "gap_x 780" "gap_x 500" $Mykodachi_path/.conkyrc0*
			rpl -i "gap_x 725" "gap_x 480" $Mykodachi_path/.conkyrc1*
			rpl -i "minimum_size 320 0" "minimum_size 220 0" $Mykodachi_path/.conkyrc1*;
			writeToJason "$newFontSize " "Screenfontsize"; 
			notify-send -i $notifyIcon "screen font size changed from: $oldFontSize to: $newFontSize"; 
		else
		if [[ $hV -lt 700 ]]
		then				
			oldFontSize=$(cat $Jason_file_name | jq -r .Screenfontsize);
			newFontSize=6;	
			rpl -i "size=$oldFontSize" "size=$newFontSize" $Mykodachi_path/.conkyrc*
			rpl -i "gap_x 350" "gap_x 220" $Mykodachi_path/.conkyrc2*
			rpl -i "gap_x 780" "gap_x 500" $Mykodachi_path/.conkyrc0*
			rpl -i "gap_x 725" "gap_x 480" $Mykodachi_path/.conkyrc1*
			rpl -i "minimum_size 320 0" "minimum_size 220 0" $Mykodachi_path/.conkyrc1*;
			writeToJason "$newFontSize " "Screenfontsize"; 
			notify-send -i $notifyIcon "screen font size changed from: $oldFontSize to: $newFontSize"; 
		fi
		fi
		fi
		fi
		fi
		fi
		
} 

# check if user has logged in
if [[ $LOGED_USER = $EXEC_USER ]]; then
	function get_res {
		echo $(xrandr -q | awk -F'current' -F',' 'NR==1 {gsub("( |current)","");print $2}')
	}
	sleep 30;
	res1=$(get_res)
    hV=$(echo $res1|cut -d x -f 2)
    fontforce=$(cat $Jason_file_name | jq -r .Forcefonts);
    screen_res=$(cat $Jason_file_name | jq -r .Screenresolution);
	if [[ "$fontforce" == *Yes* ]]
	then
		if [ "$screen_res" != "$res1" ]; then
			setTheconky;
			writeToJason "$res1" "Screenresolution";  
		fi
	fi
	while true; do
		#sleep 1
		res2=$(get_res)
		if [ "$res1" != "$res2" ]; then
			notify-send -i $notifyIcon "Screen resolution has been modified 
The display will restart now";
			sudo killall conky;	
			hV=$(echo $res2|cut -d x -f 2)
			echo $hV;
			fontforce=$(cat $Jason_file_name | jq -r .Forcefonts);
			if [[ "$fontforce" == *Yes* ]]
			then
				
				setTheconky;	
				writeToJason "$res2" "Screenresolution";  		
			
			fi

		fi
		res1=$res2
	  
	  
		sleep 15;	 
	done

fi

