#!/bin/bash
# Script written by W. Al Maawali  
# (c) 2018 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here: 
sudo echo -e 'AUTHENTICATE "Auo2@s3ks@Wdq"\r\nsignal NEWNYM\r\nQUIT' | nc 127.0.0.1 9060
notify-send "Tor exit country will be set to random country in few seconds"
exit;

