#!/bin/bash
# Script written by W. Al Maawali  
# (c) 2016 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here: 
notify-send "Restarting your network";
sudo service network-manager restart;
sudo ifconfig eth0 down;
sudo dhclient eth0;
