#!/bin/bash
# Script written by W. Al Maawali  
# (c) 2016 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

# check if user has logged in
if [[ $(who |grep 'kodachi'|cut -d : -f 1| awk 'NR==1') = *kodachi* ]]; then
	function get_res {
		echo $(xrandr -q | awk -F'current' -F',' 'NR==1 {gsub("( |current)","");print $2}')
	}
	res1=$(get_res)

	while true; do
	  sleep 10
	  res2=$(get_res)
	  if [ "$res1" != "$res2" ]; then
		sudo killall conky;
		notify-send "Screen resolution has been modified display will restart in 10 seconds";
		sleep 10;
		sudo killall conky;
		conky -c ~/.kbase/.conkyrc0;	
		conky -c ~/.kbase/.conkyrc1;	
		conky -c ~/.kbase/.conkyrc3;	
		conky -c ~/.kbase/.conkyrc2;
		
	  fi
	  res1=$res2
	done

fi

