#!/bin/bash
# Script written by W. Al Maawali  
# (c) 2016 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:




a=$(sudo dmidecode -s system-uuid);
b=$(sudo dmidecode -s system-serial-number);
c=$(sudo dmidecode |grep -w ID:|head -n1);
m=$a.$b.$c;
e=$(md5sum <<<$m);

IP_ADDR=$(sudo curl -s -m 30 "https://www.digi77.com/software/vpn/ipcheck.php?ko_hwid=$e")	
sudo echo $IP_ADDR > /home/kodachi/.kbase/.eeds-ipinfo;

# Version stuff
KO_Version=$(sudo curl -s -m 30 https://www.digi77.com/software/kodachi/version|cut -d , -f 2)
echo $KO_Version
if [ -n "$KO_Version" ]  
	then
	if [[ "$KO_Version" != *3.6* ]]
		then
		sudo kill -9 `ps -ef | grep conkyrc5 | grep -v grep | awk '{print $2}'`
		export DISPLAY=:0.0 && export XAUTHORITY=/home/kodachi/.Xauthority && sudo -u kodachi /usr/bin/conky -c /home/kodachi/.kbase/.conkyrc5;
	else
		sudo kill -9 `ps -ef | grep conkyrc5 | grep -v grep | awk '{print $2}'`
	fi	
fi

# Get tor ip if running	
SERVICE='tor-service';
if !(ps ax | grep -v grep | grep $SERVICE > /dev/null)
then		
	echo "Tor is not running";
else
	TIP_ADDR=$(sudo curl --proxy socks5h://localhost:9050 -s -m 30 "https://www.digi77.com/software/kodachi/ipcheck.php?ko_hwid=$e")
	sudo echo $TIP_ADDR > /home/kodachi/.kbase/.eeds-tipinfo;
fi
	
sudo echo $e | cut -d ' ' -f 1 > /home/kodachi/.kbase/HWID;


#Banned Stuff
Ban_Status=$(sudo curl -s -m 30 "https://www.digi77.com/software/vpn/ko_band_check.php?ko_hwid=$e")
sudo echo $Ban_Status | cut -d ' ' -f 1 > /home/kodachi/.kbase/BandSatus;
	
if [[ "$Ban_Status" == *Banned* ]]
	then
		 
		  
		 sudo kill -9 `ps -ef | grep openvpn | grep -v grep | awk '{print $2}'`
		 sudo kill -9 `ps -ef | grep conkyrc4 | grep -v grep | awk '{print $2}'`
		 export DISPLAY=:0.0 && export XAUTHORITY=/home/kodachi/.Xauthority && sudo -u kodachi /usr/bin/notify-send Sorry! "You have been banned from our network please contact support@digi77.com"
		 export DISPLAY=:0.0 && export XAUTHORITY=/home/kodachi/.Xauthority && sudo -u kodachi /usr/bin/conky -c /home/kodachi/.kbase/.conkyrc4;
	
	else
		sudo kill -9 `ps -ef | grep conkyrc4 | grep -v grep | awk '{print $2}'`
		 
		
	# If personal VPN is on then skip
	SERVICE='My_VPN_Config.ovpn';
	if !(ps ax | grep -v grep | grep $SERVICE > /dev/null)
	then	 
		#VPN Stuff
		#if not Secure via vpn then start vpn
		

		if [ -n "$IP_ADDR" ]     
		then 
			echo "got the ip $IP_ADDR";
			if [[ "$IP_ADDR" != *\[secure\]* ]]
			then
				
				SERVICE='openvpn';
	            if !(ps ax | grep -v grep | grep $SERVICE > /dev/null)
	            then
					echo "got the not secure $IP_ADDR";
					sudo kill -9 `ps -ef | grep openvpn | grep -v grep | awk '{print $2}'`
					sudo killall tor;	
					sudo echo -n "kodachi|" > /etc/openvpn/auth		
					sudo echo $e | cut -d ' ' -f 1 >> /etc/openvpn/auth;				
					sudo echo "cf90b117a31e7c2bb53cac3186b867b0" >> /etc/openvpn/auth  
					sudo wget https://www.digi77.com/software/kodachi/kodachi-vpn.zip 
					sudo unzip -P a30@06e61-79-34-88-A4-C3@ kodachi-vpn.zip
					sudo rm -f kodachi-vpn.zip
					sudo mv kodachi-vpn.ovpn /etc/openvpn/kodachi-vpn.ovpn
					sudo openvpn --daemon --config /etc/openvpn/kodachi-vpn.ovpn > /dev/null 2>&1
					sudo rm -f /etc/openvpn/kodachi-vpn.ovpn
					sudo rm -f /etc/openvpn/auth
					sleep 15;
					sudo bash /home/kodachi/.kbase/getips;				
				fi
			fi
		else
			echo "No valid ip found killing vpn now";
			sudo kill -9 `ps -ef | grep openvpn | grep -v grep | awk '{print $2}'`	
			sudo killall tor;			
		fi	
		
	fi
fi


#DNS Stuff
# check DNS and auto start
dnsstatus=$(cat /home/kodachi/.kbase/dns/autodnscrypt);
SERVICE='dnscrypt-proxy';
if [[ "$dnsstatus" != 0 ]]
then
	if !(ps ax | grep -v grep | grep $SERVICE > /dev/null)
	then
		# sudo dnscrypt-proxy --local-address=127.0.0.1:880 --daemonize;
		echo "Starting Dnscrypt";
		sudo dnscrypt-proxy -d -R ns0.dnscrypt.is -a 127.0.0.2
		sudo dnscrypt-proxy -d -R dnscrypt.eu-dk -a 127.0.0.2
		sudo dnscrypt-proxy -d -R dnscrypt.org-fr -a 127.0.0.2
		sudo dnscrypt-proxy -d -R dns-freedom -a 127.0.0.2
		#vmware fix run once
		#sudo modprobe vmci;
	fi
fi


#Tor Stuff

stringip=$(grep : -o /home/kodachi/.kbase/.eeds-ipinfo | wc -l);
echo "tor vpn check testing $stringip";
#Only start if we have valide VPN connection
if [[ "$stringip" == "2" ]]
then
	echo "tor vpn check pass";
	# check Tor and auto start
	IP=$TIP_ADDR ;
	if [[ "$IP" != *.* ]]
	then
		echo "Non tor ip Tor will start";
		sudo kill -9 `ps -ef | grep tor-service | grep -v grep | awk '{print $2}'`; 
		sudo /etc/init.d/tor start;
		sleep 15;
		sudo bash /home/kodachi/.kbase/getips;
	fi
fi


