#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2022 Founder of Eagle Eye Digital Solutions
# Discord channel https://discord.gg/KEFErEx
# Twitter http://twitter.com/warith2020
# Linkedin http://www.linkedin.com/in/warith1977
# http://www.digi77.com
# http://www.om77.net
# Kodachi  OS/Software/Code are strictly protected by LICENSE terms at /home/kodachi/LICENSE
#
#
# script starts here:

cd $(dirname $0) 
source Globalconfig;

 
sudo sed -i "/$LOGED_USER/d" /usr/share/lightdm/lightdm.conf.d/60-xubuntu.conf
sudo gpasswd -d $LOGED_USER nopasswdlogin;
notify-send -i $notifyIcon "You will be asked for user name and password at login"; 

exit 1;




