#! /bin/bash

### BEGIN INIT INFO
# Provides:          tmpcleaner
# Required-Start:    $local_fs $remote_fs dbus
# Required-Stop:     $local_fs $remote_fs dbus
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start lightdm
### END INIT INFO

# Load the VERBOSE setting and other rcS variables

rm -f -r /home/kodachi/.kbase/tmp/* 
#echo "hi" > /home/kodachi/Desktop/lol.txt

exit 0
