#!/bin/bash
# Script written by Warith Al Maawali  
# (c) 2022 Founder of Eagle Eye Digital Solutions
# Discord channel https://discord.gg/KEFErEx
# Twitter http://twitter.com/warith2020
# Linkedin http://www.linkedin.com/in/warith1977
# http://www.digi77.com
# http://www.om77.net
# Kodachi  OS/Software/Code are strictly protected by LICENSE terms at /home/kodachi/LICENSE
#
#
# script starts here:


cd $(dirname $0) 
source Globalconfig;



echo "Regenerate OpenSSH host keys on Kodachi";	
sudo dpkg-reconfigure openssh-server
sleep 1;
echo "Cleaning ssh keys"	
sudo rm -f $Myhome_path/.ssh/*		    
echo " Done..";
notify-send -i $notifyIcon "OpenSSH host keys regenerated";
exit 1;


