#!/bin/bash
# Script written by W. Al Maawali  
# (c) 2016 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here: 

# check if user has logged in
if [[ $(who |grep 'kodachi'|cut -d : -f 1| awk 'NR==1') = *kodachi* ]]; then
	
		sudo killall conky;
		notify-send "Information display will start in 10 seconds";
		sleep 10;		
		conky -c ~/.kbase/.conkyrc0;	
		conky -c ~/.kbase/.conkyrc1;	
		conky -c ~/.kbase/.conkyrc3;	
		conky -c ~/.kbase/.conkyrc2;
		sleep 15;
		exit;
	 
else
sudo killall conky;
exit;
fi



 






