#!/bin/bash
# Script written by W. Al Maawali  
# (c) 2016 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

notify-send "Only vpn traffic will be allowed";
sudo ufw disable;
sudo ufw default deny incoming;
sudo ufw default deny outgoing;
sudo ufw allow out on tun0 from any to any;
sudo ufw allow out on tun0-00 from any to any;
sudo ufw enable;

