#!/bin/bash
# Script written by W. Al Maawali  
# (c) 2016 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:


# Cron command
#* * * * * /home/kodachi/.kbase/setsudo >/dev/null 2>&1

if !(cat /etc/sudoers|grep "kodachi ALL=(ALL) NOPASSWD" > /dev/null)
then
sudo echo "kodachi ALL=(ALL:ALL) ALL" | sudo tee -a /etc/sudoers
sudo echo "kodachi ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
fi


