#!/bin/bash
# Script written by W. Al Maawali  
# (c) 2017 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

# Set global;
e="";
IP_ADDR="";
kodachi_version="3.7";

# detect empty arguments
if [ $# -eq 0 ]; then
	echo "No arguments entered"
	
	#pause 'Press [Enter] key to exit...or Ctrl c to quit the script and run it again correctly'	
        #exit 1
fi


# Accept command line arguments
while [ $# -gt 0 ]
do
    case "$1" in
    -a)  myAction=$2 ; shift;;       
	--)	shift; break;;
	-*)
	    echo >&2 \
	    "usage: $0 [-v] [-f file] [file ...]"
	    exit 1;;
	*)  break;;	# terminate while loop
    esac
    shift
done



#Set of functions
function getID()
{
       
    a=$(sudo dmidecode -s system-uuid);
	b=$(sudo dmidecode -s system-serial-number);
	c=$(sudo dmidecode |grep -w ID:|head -n1);
	m=$a.$b.$c;
	e=$(md5sum <<<$m| tr -d -|tr -d ' ');
    sudo echo $e | cut -d ' ' -f 1 > /home/kodachi/.kbase/HWID;
       
}


function getBan()
{
    getID
    #Banned Stuff
    Ban_Status=$(sudo curl -G -s -m 30 "https://www.digi77.com/software/vpn/ko_band_check.php" --data-urlencode "ko_hwid=$e" --data-urlencode "ko_ver=$kodachi_version")
    sudo echo $Ban_Status | cut -d ' ' -f 1 > /home/kodachi/.kbase/BandSatus;
}

function banAction()
{
    sudo kill -9 `ps -ef | grep openvpn | grep -v grep | awk '{print $2}'`
    sudo killall tor;   
    sudo kill -9 `ps -ef | grep conkyrc4 | grep -v grep | awk '{print $2}'`
    export DISPLAY=:0.0 && export XAUTHORITY=/home/kodachi/.Xauthority && sudo -u kodachi /usr/bin/notify-send Sorry! "You have been banned from our network please contact support@digi77.com"
    export DISPLAY=:0.0 && export XAUTHORITY=/home/kodachi/.Xauthority && sudo -u kodachi /usr/bin/conky -c /home/kodachi/.kbase/.conkyrc4;
    sudo bash /home/kodachi/.kbase/systemhealth -a getkodachiip;
    
}

function ownvpnfunction()
{    
    if grep "dev tun" /home/kodachi/Desktop/Own_VPN_Config/My_VPN_Config.ovpn > /dev/null
    then
        notify-send "Own VPN will start now"
        sudo kill -9 `ps -ef | grep openvpn | grep -v grep | awk '{print $2}'`
        sudo killall tor;
        sudo bash /home/kodachi/.kbase/systemhealth -a getnormalip;
        cd /home/kodachi/Desktop/Own_VPN_Config/ && sudo openvpn --daemon --config /home/kodachi/Desktop/Own_VPN_Config/My_VPN_Config.ovpn > /dev/null 2>&1;
        sleep 15;
        sudo bash /home/kodachi/.kbase/systemhealth -a getnormalip;
        sudo bash /home/kodachi/.kbase/systemhealth -a torstart;
        echo "Personal VPN Process Done"
        notify-send "Own VPN started successfully"
        exit;     
    else
       notify-send "VPN files are not configured yet please add your VPN configuration";
       sleep 3;
       sudo gedit /home/kodachi/Desktop/Own_VPN_Config/My_VPN_Config.ovpn;
       sudo gedit /home/kodachi/Desktop/Own_VPN_Config/auth.txt;
       exit;
    fi      
}

function kodachivpnfunction()
{
    notify-send "Kodachi VPN will start now"
    sudo kill -9 `ps -ef | grep conkyrc4 | grep -v grep | awk '{print $2}'` 		    
    sudo kill -9 `ps -ef | grep openvpn | grep -v grep | awk '{print $2}'`
    sudo killall tor;
    sleep 1;
    sudo bash /home/kodachi/.kbase/systemhealth -a getnormalip;
    sudo echo -n "kodachi|" > /etc/openvpn/auth
    sudo echo $e | cut -d ' ' -f 1 >> /etc/openvpn/auth;				
    sudo echo "cf90b117a31e7c2bb53cac3186b867b0" >> /etc/openvpn/auth  
    sudo wget "https://digi77.com/software/kodachi/kodachi-vpn.zip" -q 
    sudo unzip -P a30@06e61-79-34-88-A4-C3@ kodachi-vpn.zip
    sudo rm -f kodachi-vpn.zip
    sudo mv kodachi-vpn.ovpn /etc/openvpn/kodachi-vpn.ovpn
    sudo openvpn --daemon --config /etc/openvpn/kodachi-vpn.ovpn > /dev/null 2>&1
    sudo rm -f /etc/openvpn/kodachi-vpn.ovpn
    sudo rm -f /etc/openvpn/auth
    sleep 15;
    sudo bash /home/kodachi/.kbase/systemhealth -a getkodachiip;
    echo "kodachi VPN Process Done"
    notify-send "Kodachi VPN started successfully"    
    #Tor Stuff
    stringip=$(grep : -o /home/kodachi/.kbase/.eeds-ipinfo | wc -l);
    #echo "Tor VPN check testing $stringip";
    #Only start if we have valide VPN connection
    if [[ "$stringip" == "2" ]]
    then
        echo "tor vpn check pass";
        # check Tor and auto start
        IP=$TIP_ADDR ;
        if [[ "$IP" != *.* ]]
        then
            echo "Non tor ip Tor will start";
            sudo kill -9 `ps -ef | grep tor-service | grep -v grep | awk '{print $2}'`; 
            sudo bash /home/kodachi/.kbase/systemhealth -a torstart;
        fi
    fi    
    exit;	
}

if [[ "$myAction" == *getkodachiip* ]]
then

	getID
	IP_ADDR=$(sudo curl -G -s -m 30 "https://www.digi77.com/software/vpn/ipcheck.php" --data-urlencode "ko_hwid=$e" --data-urlencode "ko_ver=$kodachi_version")	
	echo "The Kodachi ip:" $IP_ADDR;
	sudo echo $IP_ADDR > /home/kodachi/.kbase/.eeds-ipinfo;
	exit;


fi
if [[ "$myAction" == *getnormalip* ]]
then

	 
	IP_ADDR=$(sudo curl -s -m 30 "https://www.digi77.com/software/vpn/ipcheck.php")	
	echo "The Normal ip:" $IP_ADDR;
	sudo echo $IP_ADDR > /home/kodachi/.kbase/.eeds-ipinfo;
	exit;


fi
if [[ "$myAction" == *gettorip* ]]
then

	SERVICE='tor-service';
	if !(ps ax | grep -v grep | grep $SERVICE > /dev/null)
	then		
		echo "Tor is not running";
	else
		TIP_ADDR=$(sudo curl --proxy socks5h://localhost:9050 -s -m 30 "https://www.digi77.com/software/vpn/ipcheck.php")
		echo "The Tor ip:" $TIP_ADDR;
		sudo echo $TIP_ADDR > /home/kodachi/.kbase/.eeds-tipinfo;
	fi
	exit;	
fi


if [[ "$myAction" == *kodachivpn* ]]
then
    getID
    getBan
    sudo echo "kodachivpn" > /home/kodachi/.kbase/vpntype;
    if [[ "$Ban_Status" == *Banned* ]]
	then
		banAction 	
	else
        kodachivpnfunction		
	fi
fi



if [[ "$myAction" == *ownvpn* ]]
then
    sudo echo "ownvpn" > /home/kodachi/.kbase/vpntype; 
    ownvpnfunction     
fi


if [[ "$myAction" == *stopvpn* ]]
then
    sudo echo "novpn" > /home/kodachi/.kbase/vpntype; 
	sudo kill -9 `ps -ef | grep openvpn | grep -v grep | awk '{print $2}'`
    sudo echo "" > /home/kodachi/.kbase/.eeds-ipinfo;
    sleep 2;
    sudo bash /home/kodachi/.kbase/systemhealth -a getnormalip;
    sudo bash /home/kodachi/.kbase/systemhealth -a stoptor;
    echo "Stop VPN Process Done"
    notify-send "VPN Stopped successfully"
    exit;
fi

if [[ "$myAction" == *stoptor* ]]
then     
	sudo killall tor;     
    echo "Tor Stopped Process Done"
    notify-send "Tor Stopped successfully"
    exit;
fi

if [[ "$myAction" == *torstart* ]]
then     
	sudo killall tor;    
    sudo echo "" > /home/kodachi/.kbase/.eeds-tipinfo;
    sudo /etc/init.d/tor start;
    echo "Tor Start Process Done"
    sleep 15;
    sudo bash /home/kodachi/.kbase/systemhealth -a gettorip;
    notify-send "Tor Started successfully"
    exit;
fi
  
    
    
# Start Cron Part will run every 1 min    
 
#DNS Stuff
# check DNS and auto start
dnsstatus=$(cat /home/kodachi/.kbase/dns/autodnscrypt);
SERVICE='dnscrypt-proxy';
if [[ "$dnsstatus" != 0 ]]
then
	if !(ps ax | grep -v grep | grep $SERVICE > /dev/null)
	then
		# sudo dnscrypt-proxy --local-address=127.0.0.1:880 --daemonize;
		echo "Starting Dnscrypt";
		sudo dnscrypt-proxy -d -R ns0.dnscrypt.is -a 127.0.0.2
		sudo dnscrypt-proxy -d -R dnscrypt.eu-dk -a 127.0.0.2
		sudo dnscrypt-proxy -d -R dnscrypt.org-fr -a 127.0.0.2
		sudo dnscrypt-proxy -d -R dnscrypt.eu-nl -a 127.0.0.2
		#vmware fix run once
		#sudo modprobe vmci;
	fi
fi


# Version stuff
KO_Version=$(sudo curl -s -m 30 https://www.digi77.com/software/kodachi/version|cut -d , -f 2)
echo "Kodachi Net Version is: " $KO_Version;
sudo echo $KO_Version > /home/kodachi/.kbase/version;

if [ -n "$KO_Version" ]  
	then
	if [[ "$KO_Version" != *$kodachi_version* ]]
		then
		sudo kill -9 `ps -ef | grep conkyrc5 | grep -v grep | awk '{print $2}'`
		export DISPLAY=:0.0 && export XAUTHORITY=/home/kodachi/.Xauthority && sudo -u kodachi /usr/bin/conky -c /home/kodachi/.kbase/.conkyrc5;
	else
		sudo kill -9 `ps -ef | grep conkyrc5 | grep -v grep | awk '{print $2}'`
	fi	
fi 
 
 
# Get IPS
getID
getBan

# Get VPN Type and IP
vpntype=$(cat /home/kodachi/.kbase/vpntype|tr -d ' ');
#
echo "VPN type is:" $vpntype;


if [[ "$vpntype" != *ownvpn* ]]
then
    IP_ADDR=$(sudo curl -G -s -m 30 "https://www.digi77.com/software/vpn/ipcheck.php" --data-urlencode "ko_hwid=$e" --data-urlencode "ko_ver=$kodachi_version")	
    echo "The Kodachi ip:" $IP_ADDR;
    sudo echo $IP_ADDR > /home/kodachi/.kbase/.eeds-ipinfo;
else
    IP_ADDR=$(sudo curl -s -m 30 "https://www.digi77.com/software/vpn/ipcheck.php")	
	echo "The Normal ip:" $IP_ADDR;
    sudo echo $IP_ADDR > /home/kodachi/.kbase/.eeds-ipinfo;
fi



if [[ "$Ban_Status" == *Banned* ]]
then
    if [[ "$vpntype" == *ownvpn* ]]
    then
        sudo kill -9 `ps -ef | grep conkyrc4 | grep -v grep | awk '{print $2}'` 
    else
        banAction        
    fi 
else
    sudo kill -9 `ps -ef | grep conkyrc4 | grep -v grep | awk '{print $2}'`
fi






# Get Tor ip if VPN and Tor are running	
SERVICE='tor-service';
if (ps ax | grep -v grep | grep $SERVICE > /dev/null)
then
    SERVICE='openvpn';
    if (ps ax | grep -v grep | grep $SERVICE > /dev/null)
    then
        sudo bash /home/kodachi/.kbase/systemhealth -a gettorip;
    fi
fi





if [[ "$vpntype" == *novpn* ]]
then
     SERVICE='openvpn';
    if (ps ax | grep -v grep | grep $SERVICE > /dev/null)
    then    
        sudo bash /home/kodachi/.kbase/systemhealth -a stopvpn;
    fi
fi


if [[ "$vpntype" == *ownvpn* ]]
then
    
    
    SERVICE='openvpn';
    if !(ps ax | grep -v grep | grep $SERVICE > /dev/null)
    then
        ownvpnfunction
    else    
        if [ -n "$IP_ADDR" ]     
        then 
            # If personal VPN is on then skip
            SERVICE='My_VPN_Config.ovpn';
            if !(ps ax | grep -v grep | grep $SERVICE > /dev/null)
            then
               ownvpnfunction      
            fi
        else
            echo "No valid ip found killing ownvpn now";
            sudo kill -9 `ps -ef | grep openvpn | grep -v grep | awk '{print $2}'`	
            sudo killall tor;			
        fi
    fi    
fi

 

if [[ "$vpntype" == *kodachivpn* ]]
then
     
     if [[ "$Ban_Status" == *Banned* ]]
	then
		banAction 	
	else
    
        SERVICE='openvpn';
        if !(ps ax | grep -v grep | grep $SERVICE > /dev/null)
        then
            kodachivpnfunction
        else        
            if [ -n "$IP_ADDR" ]     
             then 
                echo "got the ip $IP_ADDR";
                if [[ "$IP_ADDR" != *\[secure\]* ]]
                then
                    kodachivpnfunction                 
                fi
            else
                 echo "No valid ip found killing Kodachi vpn now";
                 sudo kill -9 `ps -ef | grep openvpn | grep -v grep | awk '{print $2}'`	
                 sudo killall tor;			
            fi	
        fi
    fi   
fi

 

# Run tor if not running
SERVICE='tor-service';
if !(ps ax | grep -v grep | grep $SERVICE > /dev/null)
then
    SERVICE='openvpn';
    if (ps ax | grep -v grep | grep $SERVICE > /dev/null)
    then
        sudo bash /home/kodachi/.kbase/systemhealth -a torstart;
    fi
fi


#Nothing to do exit
exit;    






	









