#!/bin/bash
# Script written by W. Al Maawali  
# (c) 2016 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here:

echo "Killing VPN Process...."
sudo sed -i 's/\bnotsecure\b/secure/' /home/kodachi/.kbase/systemhealth 
sudo kill -9 `ps -ef | grep openvpn | grep -v grep | awk '{print $2}'`
sudo killall tor;
sudo bash /home/kodachi/.kbase/getips;
sudo echo -n "kodachi|" > /etc/openvpn/auth
a=$(sudo dmidecode -s system-uuid);
b=$(sudo dmidecode -s system-serial-number);
c=$(sudo dmidecode |grep -w ID:|head -n1);
m=$a.$b.$c;
e=$(md5sum <<<$m);
sudo echo $e | cut -d ' ' -f 1 >> /etc/openvpn/auth;
sudo echo "cf90b117a31e7c2bb53cac3186b867b0" >> /etc/openvpn/auth  
sudo wget https://www.digi77.com/software/kodachi/kodachi-vpn.zip 
sudo unzip -P a30@06e61-79-34-88-A4-C3@ kodachi-vpn.zip
sudo rm -f kodachi-vpn.zip
sudo rm -f /root/kodachi-vpn.zip
sudo mv kodachi-vpn.ovpn /etc/openvpn/kodachi-vpn.ovpn
sudo openvpn --daemon --config /etc/openvpn/kodachi-vpn.ovpn > /dev/null 2>&1
sudo rm -f /etc/openvpn/kodachi-vpn.ovpn
sudo rm -f /etc/openvpn/auth
sleep 15;
sudo bash /home/kodachi/.kbase/getips;
echo "Done"





