#!/bin/bash
# Script written by W. Al Maawali  
# (c) 2016 Founder of Eagle Eye Digital Solutions
# http://www.digi77.com
# http://www.om77.net
# script starts here: 
notify-send "Wiping RAM and shutting now";
sudo sdmem -v;
sudo shutdown -h now;
