#! /bin/sh
### BEGIN INIT INFO
# Provides:          bodhibuilder-firstboot
# Required-Start:    $remote_fs $syslog $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run firstboot items for bodhibuilder after a remastered system has been installed
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
    #REM302
    if [ "`cat /proc/cmdline | grep casper`" = "" ]; then # run thru this if it's NOT an ISO
        [ "$VERBOSE" != no ] && log_begin_msg "Running bodhibuilder-firstboot"
        #Warith	
	slay kodachi
	usermod -u 1000 kodachi 
        # Removes this script from boot:
        (sleep 60 && update-rc.d -f bodhibuilder-firstboot remove) &
        sed -i -e 's/root:x:/root:!:/g' /etc/shadow
        ## Ubiquity
            # Remove ubiquity icon from desktop
            yes | rm -rf /home/*/Desktop/ubiquity*.desktop
            yes | rm -rf /home/*/Desktop/UBIQUITY*.desktop
            yes | rm -rf /usr/share/applications/UBIQUITY.desktop
            # Remove ubiquity from menus
            sed -i -e 's/NoDisplay=false/NoDisplay=true/' /usr/share/applications/ubiquity.desktop
            sed -i -e 's/Hidden=false/Hidden=true/' /usr/share/applications/ubiquity.desktop

        # Create bodhibuilder desktop file for menus
        yes | cp -f /etc/bodhibuilder/applications/bodhibuilder-gtk.desktop /usr/share/applications/

        # Restore sources.list from source OS
        if [ -e /etc/bodhibuilder/apt/sources.list_BB ] ; then
          yes | mv /etc/apt/sources.list /etc/apt/sources.list_ORIG
          yes | mv /etc/bodhibuilder/apt/sources.list_BB /etc/apt/sources.list
          sleep 1
        fi
        # Remove any remaining cdrom repos that may be in sources.list
        sed -i '/cdrom:/d' /etc/apt/sources.list &> /dev/null

        # Replace OS grub with bodhibuilder's custom grub
        yes | cp -f /etc/default/grub.bodhi /etc/default/grub
        sed -i "s/^DISTRIB_DESCRIPTION=.*$/DISTRIB_DESCRIPTION=\"__DISTNAME__\"/" /etc/lsb-release
        update-grub

        ################################################
        ### CUSTOM COMMANDS
        #
        # Commands entered into this section will be run only when
        # after the system has been installed and booted for the
        # first time, and never again.
        #
        ### Place your custom commands below this line
        #WARITH
	apt-get purge bodhibuilder --yes --assume-yes
        apt-get --yes --assume-yes autoremove
        
        
        ### Place your custom commands above this line
        ################################################
        
        ES=$?
        [ "$VERBOSE" != no ] && log_end_msg $ES
        return $ES
    else # run through this if it IS an ISO
        logger bodhibuilder ISO booted
        sleep 1
        # Remove any cdrom: repos that may be in sources.list
        sed -i '/cdrom:/d' /etc/apt/sources.list &> /dev/null
        
    fi
}


case "$1" in
    start)
        do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

